package com.open.numberManagement.entity;
// Generated Feb 10, 2018 1:15:48 AM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.PreRemove;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Permissions generated by hbm2java
 */
@Entity
@EntityListeners(AuditingEntityListener.class)
@Data
@Setter
@Getter
@NoArgsConstructor
@Table(name = "permissions", catalog = "openNM")
public class Permission implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "name", nullable = false, unique = true, length = 50)
	private String name;
	@Column(name = "descr", nullable = false, length = 200)
	private String descr;
	@CreatedBy
	@Column(name = "row_added_user", nullable = false, length = 50)
	private String rowAddedUser;
	@CreatedDate
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "row_added_dttm", nullable = false, length = 19)
	@JsonIgnore
	private Date rowAddedDttm;
	@LastModifiedBy
	@Column(name = "row_updated_user", nullable = false, length = 50)
	private String rowUpdatedUser;
	@LastModifiedDate
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "row_updated_dttm", nullable = false, length = 19)
	@JsonIgnore
	private Date rowUpdatedDttm;

	public Permission(String name, String descr) {
		this.name = name;
		this.descr = descr;
	}
	
	public Permission(String name, String descr, String rowAddedUser, Date rowAddedDttm, String rowUpdatedUser,
			Date rowUpdatedDttm) {
		this.name = name;
		this.descr = descr;
		this.rowAddedUser = rowAddedUser;
		this.rowAddedDttm = rowAddedDttm;
		this.rowUpdatedUser = rowUpdatedUser;
		this.rowUpdatedDttm = rowUpdatedDttm;
	}

}
