package com.open.numberManagement.entity;
// Generated Feb 10, 2018 1:15:48 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Permissions2resourcetypeId generated by hbm2java
 */
@Embeddable
public class Permissions2resourcetypeId implements java.io.Serializable {

	private int permId;
	private int resTypeId;

	public Permissions2resourcetypeId() {
	}

	public Permissions2resourcetypeId(int permId, int resTypeId) {
		this.permId = permId;
		this.resTypeId = resTypeId;
	}

	@Column(name = "perm_id", nullable = false)
	public int getPermId() {
		return this.permId;
	}

	public void setPermId(int permId) {
		this.permId = permId;
	}

	@Column(name = "res_type_id", nullable = false)
	public int getResTypeId() {
		return this.resTypeId;
	}

	public void setResTypeId(int resTypeId) {
		this.resTypeId = resTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Permissions2resourcetypeId))
			return false;
		Permissions2resourcetypeId castOther = (Permissions2resourcetypeId) other;

		return (this.getPermId() == castOther.getPermId()) && (this.getResTypeId() == castOther.getResTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPermId();
		result = 37 * result + this.getResTypeId();
		return result;
	}

}
