package com.open.numberManagement.entity;
// Generated Feb 10, 2018 1:15:48 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Permissions2resourcetype generated by hbm2java
 */
@Entity
@Table(name = "permissions2resourcetype", catalog = "openNM")
public class Permissions2resourcetype implements java.io.Serializable {

	private Permissions2resourcetypeId id;
	private String rowAddedUser;
	private Date rowAddedDttm;

	public Permissions2resourcetype() {
	}

	public Permissions2resourcetype(Permissions2resourcetypeId id, String rowAddedUser, Date rowAddedDttm) {
		this.id = id;
		this.rowAddedUser = rowAddedUser;
		this.rowAddedDttm = rowAddedDttm;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "permId", column = @Column(name = "perm_id", nullable = false)),
			@AttributeOverride(name = "resTypeId", column = @Column(name = "res_type_id", nullable = false)) })
	public Permissions2resourcetypeId getId() {
		return this.id;
	}

	public void setId(Permissions2resourcetypeId id) {
		this.id = id;
	}

	@Column(name = "row_added_user", nullable = false, length = 50)
	public String getRowAddedUser() {
		return this.rowAddedUser;
	}

	public void setRowAddedUser(String rowAddedUser) {
		this.rowAddedUser = rowAddedUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "row_added_dttm", nullable = false, length = 19)
	public Date getRowAddedDttm() {
		return this.rowAddedDttm;
	}

	public void setRowAddedDttm(Date rowAddedDttm) {
		this.rowAddedDttm = rowAddedDttm;
	}

}
