package com.open.numberManagement.entity;
// Generated Feb 10, 2018 1:15:48 AM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.PreRemove;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Permissions generated by hbm2java
 */
@Entity
@Data
@Setter
@Getter
@NoArgsConstructor
@Table(name = "permissions", catalog = "openNM")
public class Permission implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "name", nullable = false, unique = true, length = 50)
	private String name;
	@Column(name = "descr", nullable = false, length = 200)
	private String descr;
	@Column(name = "row_added_user", nullable = false, length = 50)
	private String rowAddedUser;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "row_added_dttm", nullable = false, length = 19)
	@JsonIgnore
	private Date rowAddedDttm = new Date();
	@Column(name = "row_updated_user", nullable = false, length = 50)
	private String rowUpdatedUser;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "row_updated_dttm", nullable = false, length = 19)
	@JsonIgnore
	private Date rowUpdatedDttm = new Date();

	public Permission(String name, String descr, String rowAddedUser, String rowUpdatedUser) {
		this.name = name;
		this.descr = descr;
		this.rowAddedUser = rowAddedUser;
		this.rowUpdatedUser = rowUpdatedUser;
	}
	
	public Permission(String name, String descr, String rowAddedUser, Date rowAddedDttm, String rowUpdatedUser,
			Date rowUpdatedDttm) {
		this.name = name;
		this.descr = descr;
		this.rowAddedUser = rowAddedUser;
		this.rowAddedDttm = rowAddedDttm;
		this.rowUpdatedUser = rowUpdatedUser;
		this.rowUpdatedDttm = rowUpdatedDttm;
	}
	
    /*@PrePersist
    public void onPrePersist() {
    	Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
    	String currentPrincipalName = authentication.getName();
    	this.rowAddedUser = currentPrincipalName;
    	this.rowAddedDttm = (new Date());
    }
      
    @PreUpdate
    public void onPreUpdate() {
    	Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
    	String currentPrincipalName = authentication.getName();
    	this.rowUpdatedUser = currentPrincipalName;
    	this.rowUpdatedDttm = (new Date());
    }
      
    @PreRemove
    public void onPreRemove() {
        System.out.print("Row deleted");
    }	*/

}
