package com.open.numberManagement.entity;
// Generated Feb 10, 2018 1:15:48 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ResourceType generated by hbm2java
 */
@Entity
@EntityListeners(AuditingEntityListener.class)
@Table(name = "resource_type", catalog = "openNM", uniqueConstraints = { @UniqueConstraint(columnNames = "length"),
		@UniqueConstraint(columnNames = "name"), @UniqueConstraint(columnNames = "prefix") })
public class ResourceType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String descr;
	private int length;
	private int prefix;
	private int reservationTime;
	private String rowAddedUser;
	private Date rowAddedDttm;
	private String rowUpdatedUser;
	private Date rowUpdatedDttm;

	/* TO DO!!!
	@JsonIgnore
	@ManyToMany(mappedBy = "resourceTypes")
	private Set<Permission> permissions = new HashSet<>();

	public Set<Permission> getPermissions() {
		return permissions;
	}

	public void setPermissions(Set<Permission> permissions) {
		this.permissions = permissions;
	}*/
	
	public ResourceType() {
	}

	public ResourceType(String name, String descr, int length, int prefix, int reservationTime) {
		this.name = name;
		this.descr = descr;
		this.length = length;
		this.prefix = prefix;
		this.reservationTime = reservationTime;
	}

	public ResourceType(String name, String descr, int length, int prefix, int reservationTime, String rowAddedUser,
			Date rowAddedDttm, String rowUpdatedUser, Date rowUpdatedDttm) {
		this.name = name;
		this.descr = descr;
		this.length = length;
		this.prefix = prefix;
		this.reservationTime = reservationTime;
		this.rowAddedUser = rowAddedUser;
		this.rowAddedDttm = rowAddedDttm;
		this.rowUpdatedUser = rowUpdatedUser;
		this.rowUpdatedDttm = rowUpdatedDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "descr", nullable = false, length = 200)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name = "length", unique = true, nullable = false)
	public int getLength() {
		return this.length;
	}

	public void setLength(int length) {
		this.length = length;
	}

	@Column(name = "prefix", unique = true, nullable = false)
	public int getPrefix() {
		return this.prefix;
	}

	public void setPrefix(int prefix) {
		this.prefix = prefix;
	}

	@Column(name = "reservation_time", nullable = false)
	public int getReservationTime() {
		return this.reservationTime;
	}

	public void setReservationTime(int reservationTime) {
		this.reservationTime = reservationTime;
	}

	@CreatedBy
	@Column(name = "row_added_user", nullable = false, length = 50)
	public String getRowAddedUser() {
		return this.rowAddedUser;
	}

	public void setRowAddedUser(String rowAddedUser) {
		this.rowAddedUser = rowAddedUser;
	}

	@CreatedDate
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "row_added_dttm", nullable = false, length = 19)
	public Date getRowAddedDttm() {
		return this.rowAddedDttm;
	}

	public void setRowAddedDttm(Date rowAddedDttm) {
		this.rowAddedDttm = rowAddedDttm;
	}

	@LastModifiedBy
	@Column(name = "row_updated_user", nullable = false, length = 50)
	public String getRowUpdatedUser() {
		return this.rowUpdatedUser;
	}

	public void setRowUpdatedUser(String rowUpdatedUser) {
		this.rowUpdatedUser = rowUpdatedUser;
	}

	@LastModifiedDate
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "row_updated_dttm", nullable = false, length = 19)
	public Date getRowUpdatedDttm() {
		return this.rowUpdatedDttm;
	}

	public void setRowUpdatedDttm(Date rowUpdatedDttm) {
		this.rowUpdatedDttm = rowUpdatedDttm;
	}

}
