package com.open.numberManagement.entity;
// Generated Feb 10, 2018 1:15:48 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * ResourceHistory generated by hbm2java
 */
@Entity
@EntityListeners(AuditingEntityListener.class)
@Table(name = "resource_history", catalog = "openNM")
public class ResourceHistory implements java.io.Serializable {
	
	private Integer id;
	private int resId;
	private Integer sourceStatusId;
	private int targetStatusId;
	private String rowAddedUser;
	private Date rowAddedDttm = new Date();

	public ResourceHistory() {
	}

	public ResourceHistory(int resId, Integer sourceStatusId, int targetStatusId) {
		this.resId = resId;
		this.sourceStatusId = sourceStatusId;
		this.targetStatusId = targetStatusId;
	}
	
	public ResourceHistory(int resId, int sourceStatusId, int targetStatusId, String rowAddedUser, Date rowAddedDttm) {
		this.resId = resId;
		this.sourceStatusId = sourceStatusId;
		this.targetStatusId = targetStatusId;
		this.rowAddedUser = rowAddedUser;
		this.rowAddedDttm = rowAddedDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "res_id", nullable = false)
	public int getResId() {
		return this.resId;
	}

	public void setResId(int resId) {
		this.resId = resId;
	}

	@Column(name = "source_status_id", nullable = true)
	public Integer getSourceStatusId() {
		return this.sourceStatusId;
	}

	public void setSourceStatusId(Integer sourceStatusId) {
		this.sourceStatusId = sourceStatusId;
	}

	@Column(name = "target_status_id", nullable = false)
	public int getTargetStatusId() {
		return this.targetStatusId;
	}

	public void setTargetStatusId(int targetStatusId) {
		this.targetStatusId = targetStatusId;
	}

	@CreatedBy
	@Column(name = "row_added_user", nullable = false, length = 50)
	public String getRowAddedUser() {
		return this.rowAddedUser;
	}

	public void setRowAddedUser(String rowAddedUser) {
		this.rowAddedUser = rowAddedUser;
	}

	@CreatedDate
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "row_added_dttm", nullable = false, length = 19)
	public Date getRowAddedDttm() {
		return this.rowAddedDttm;
	}

	public void setRowAddedDttm(Date rowAddedDttm) {
		this.rowAddedDttm = rowAddedDttm;
	}

}
