package com.open.numberManagement.entity;
// Generated Feb 10, 2018 1:15:48 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * ResourceHistory generated by hbm2java
 */
@Entity
@EntityListeners(AuditingEntityListener.class)
@Table(name = "resource_history", catalog = "openNM")
public class ResourceHistory implements java.io.Serializable {

	private Integer id;
	private int resId;
	private Integer sourceStatusId;
	
	private ResourceStatus sourceStatus;
	
	private int targetStatusId;
	
	private ResourceStatus targetStatus;
	
	private Integer oldRelResId;
	// Hibernate issue??
	//When I uncomment the following row then Resource.RelatedResource null pointer issue appear! 
	//private Resource oldRelatedResource;
	
	private Integer newRelResId;
	
	private Resource newRelatedResource;
	
	private String oldDescr;
	private String newDescr;
	private String rowAddedUser;
	private Date rowAddedDttm = new Date();

	public ResourceHistory() {
	}

	public ResourceHistory(int resId, Integer sourceStatusId, int targetStatusId) {
		this.resId = resId;
		this.sourceStatusId = sourceStatusId;
		this.targetStatusId = targetStatusId;
	}

	public ResourceHistory(int resId, Integer sourceStatusId, int targetStatusId, Integer oldRelResId,
			Integer newRelResId) {
		this.resId = resId;
		this.sourceStatusId = sourceStatusId;
		this.targetStatusId = targetStatusId;
		this.oldRelResId = oldRelResId;
		this.newRelResId = newRelResId;
	}

	public ResourceHistory(int resId, Integer sourceStatusId, int targetStatusId, Integer oldRelResId,
			Integer newRelResId, String oldDescr, String newDescr) {
		this.resId = resId;
		this.sourceStatusId = sourceStatusId;
		this.targetStatusId = targetStatusId;
		this.oldRelResId = oldRelResId;
		this.newRelResId = newRelResId;
		this.oldDescr = oldDescr;
		this.newDescr = newDescr;
	}

	public ResourceHistory(int resId, int sourceStatusId, int targetStatusId, Integer oldRelResId, Integer newRelResId,
			String rowAddedUser, Date rowAddedDttm, String oldDescr, String newDescr) {
		this.resId = resId;
		this.sourceStatusId = sourceStatusId;
		this.targetStatusId = targetStatusId;
		this.oldRelResId = oldRelResId;
		this.newRelResId = newRelResId;
		this.rowAddedUser = rowAddedUser;
		this.rowAddedDttm = rowAddedDttm;
		this.oldDescr = oldDescr;
		this.newDescr = newDescr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "res_id", nullable = false)
	public int getResId() {
		return this.resId;
	}

	public void setResId(int resId) {
		this.resId = resId;
	}

	@Column(name = "source_status_id", nullable = true)
	public Integer getSourceStatusId() {
		return this.sourceStatusId;
	}

	public void setSourceStatusId(Integer sourceStatusId) {
		this.sourceStatusId = sourceStatusId;
	}

	@Column(name = "target_status_id", nullable = false)
	public int getTargetStatusId() {
		return this.targetStatusId;
	}

	public void setTargetStatusId(int targetStatusId) {
		this.targetStatusId = targetStatusId;
	}

	@Column(name = "old_rel_res_id", nullable = true)
	public Integer getOldRelResId() {
		return oldRelResId;
	}

	public void setOldRelResId(Integer oldRelResId) {
		this.oldRelResId = oldRelResId;
	}

	@Column(name = "new_rel_res_id", nullable = true)
	public Integer getNewRelResId() {
		return newRelResId;
	}

	public void setNewRelResId(Integer newRelResId) {
		this.newRelResId = newRelResId;
	}

	@Column(name = "old_descr", nullable = true)
	public String getOldDescr() {
		return oldDescr;
	}

	public void setOldDescr(String oldDescr) {
		this.oldDescr = oldDescr;
	}

	@Column(name = "new_descr", nullable = true)
	public String getNewDescr() {
		return newDescr;
	}

	public void setNewDescr(String newDescr) {
		this.newDescr = newDescr;
	}

	@CreatedBy
	@Column(name = "row_added_user", nullable = false, length = 50)
	public String getRowAddedUser() {
		return this.rowAddedUser;
	}

	public void setRowAddedUser(String rowAddedUser) {
		this.rowAddedUser = rowAddedUser;
	}

	@CreatedDate
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "row_added_dttm", nullable = false, length = 19)
	public Date getRowAddedDttm() {
		return this.rowAddedDttm;
	}

	public void setRowAddedDttm(Date rowAddedDttm) {
		this.rowAddedDttm = rowAddedDttm;
	}

	@OneToOne(fetch = FetchType.EAGER, optional = true)
    @JoinColumn(name = "source_status_id", insertable = false, updatable = false)   
	public ResourceStatus getSourceStatus() {
		return sourceStatus;
	}

	public void setSourceStatus(ResourceStatus sourceStatus) {
		this.sourceStatus = sourceStatus;
	}

	@OneToOne(fetch = FetchType.EAGER, optional = true)
    @JoinColumn(name = "target_status_id", insertable = false, updatable = false) 
	public ResourceStatus getTargetStatus() {
		return targetStatus;
	}

	public void setTargetStatus(ResourceStatus targetStatus) {
		this.targetStatus = targetStatus;
	}

	/*@OneToOne(fetch = FetchType.EAGER, optional = true)
    @JoinColumn(name = "old_rel_res_id", insertable = false, updatable = false) 
	public Resource getOldRelatedResource() {
		return oldRelatedResource;
	}

	public void setOldRelatedResource(Resource oldRelatedResource) {
		this.oldRelatedResource = oldRelatedResource;
	}*/

	@OneToOne(fetch = FetchType.EAGER, optional = true)
    @JoinColumn(name = "new_rel_res_id", insertable = false, updatable = false) 
	public Resource getNewRelatedResource() {
		return newRelatedResource;
	}

	public void setNewRelatedResource(Resource newRelatedResource) {
		this.newRelatedResource = newRelatedResource;
	}

	
}
