package com.open.numberManagement.service.repository;

import static com.open.numberManagement.util.Constants.ADMINISTRATOR_PERMISSION;
import com.open.numberManagement.entity.Permission;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.Description;
import org.springframework.data.rest.core.annotation.RestResource;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 10/02/2018
*/
@Repository
@PreAuthorize("hasAuthority('" + ADMINISTRATOR_PERMISSION + "')")
public interface PermissionRepository extends JpaRepository<Permission, Integer>, JpaSpecificationExecutor<Permission>, PagingAndSortingRepository<Permission, Integer> {

	@Description(value = "Get Permission by Name")
	@RestResource(path = "byname", rel="permissions")
	@Query("select p from Permission p where p.name = :name")
	Permission getPermissionByName(@Param("name") String name);
}
