package com.open.numberManagement.service.repository;

import com.open.numberManagement.entity.ResourceLifecycle;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 10/02/2018
*/
@Repository
public interface ResourceLifecycleRepository extends JpaRepository<ResourceLifecycle, Integer>, JpaSpecificationExecutor<ResourceLifecycle> {

}
