package com.open.numberManagement.service.repository;

import com.open.numberManagement.entity.ResourceLifecycle;
import com.open.numberManagement.entity.ResourceStatus;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.Description;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 10/02/2018
*/
@Repository
@PreAuthorize("hasAuthority('ADMIN_PERM')")
public interface ResourceLifecycleRepository extends JpaRepository<ResourceLifecycle, Integer>, JpaSpecificationExecutor<ResourceLifecycle> {

	@PreAuthorize("isAuthenticated()")
	@Description(value = "Get Target Status Ids by Source Status Id")
	@Query("select rs from ResourceLifecycle rl, ResourceStatus rs where rl.sourceStatusId = :sourceStatusId and rs.id = rl.targetStatusId")
	List<ResourceStatus> getTargetStatusesBySourceStatusId(@Param("sourceStatusId") Integer sourceStatusId);
}
