package com.open.numberManagement.service.repository;

import com.open.numberManagement.entity.Role;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.Description;
import org.springframework.data.rest.core.annotation.RestResource;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 10/02/2018
*/
@Repository
@PreAuthorize("hasAuthority('ADMIN_PERM')")
public interface RoleRepository extends JpaRepository<Role, Integer>, JpaSpecificationExecutor<Role>, PagingAndSortingRepository<Role, Integer> {

	@Description(value = "Get Role by Name")
	@RestResource(path = "byname", rel="roles")
	@Query("select r from Role r where r.name = :name")
	Role getRoleByName(@Param("name") String name);
}
