package com.open.numberManagement.service.repository;

import static com.open.numberManagement.util.Constants.ADMINISTRATOR_PERMISSION;
import com.open.numberManagement.entity.Role2permission;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Repository;
import com.open.numberManagement.entity.Roles2permissionsId;

/**
* Generated by Spring Data Generator on 10/02/2018
*/
@Repository
@PreAuthorize("hasAuthority('" + ADMINISTRATOR_PERMISSION + "')")
public interface Role2permissionRepository extends JpaRepository<Role2permission, Roles2permissionsId>, JpaSpecificationExecutor<Role2permission> {

}
