package com.open.numberManagement.service.repository;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.Description;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.stereotype.Repository;

import com.open.numberManagement.entity.User;

/**
* Generated by Spring Data Generator on 10/02/2018
*/
@Repository
@RepositoryRestResource(exported = false)
public interface UserRepository extends JpaRepository<User, Integer>, JpaSpecificationExecutor<User> {

	@Description(value = "Get User by id")
	@Query("select u from User u where u.id = :id")
	Optional<User> getUser(@Param("id") Integer id);
	
	@Description(value = "Get User by login")
	@Query("select u from User u where u.login = :login")
	Optional<User> getUserByLogin(@Param("login") String login);
}
